---
title: "dash_plots"
author: "Braden Tam"
date: "07/12/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scales)

unemply_df_year <- read_csv("data/unemply_df_year.csv")
unemply_df_month <- read_csv("data/unemply_df_month.csv")


df <- unemply_df_year %>%
  select(-c(count, rate, X1))

df <- df  %>%
  spread(key = 'year', value = 'total')


# plot 1
make_plot_1 <- function(year_range = c(2000, 2003), stat = "rate"){

  new_df <- df %>%
    select(industry)
  if(stat == "rate"){
    new_df$rate <- unlist(round((df[as.character(year_range[2])] - 
                                   df[as.character(year_range[1])]) / df[as.character(year_range[1])], 2))
    new_df <- new_df %>%
       mutate(colour = ifelse(rate < 0, "type1", "type2"))

    ggplot(new_df, aes(industry, rate, colour = colour)) + 
      geom_segment(aes(xend = industry, y = 0, yend = rate)) +
      geom_point(size = 2) + 
      coord_flip() + 
      scale_y_continuous(labels = percent_format(accuracy = 1L)) + 
      theme(legend.position = "none") +
      labs(x = '', y = 'Percentage Change')
  
  } else {
    new_df$count <- unlist(round((df[as.character(year_range[2])] - df[as.character(year_range[1])])))
    new_df <- new_df %>%
      mutate(colour = ifelse(count < 0, "type1", "type2"))
  
    ggplot(new_df, aes(industry, count, colour = colour)) + 
      geom_segment(aes(xend = industry, y = 0, yend = count)) +
      geom_point(size = 2) + 
      coord_flip() + 
      theme(legend.position = "none") +
      labs(x = ' ', y = 'Absolute Change')
  }
}

# plot 2
make_plot_2 <- function(industries = c("Agriculture", "Construction"), stat = "rate"){
  avg_df <- unemply_df_year %>%
    group_by(year) %>%
    summarize(rate = mean(rate),
              count = mean(count))
  
  new_df <- unemply_df_year %>%
    filter(industry %in% industries)
  if(stat == "rate"){
    ggplot() + 
      geom_line(new_df, mapping = aes(factor(year), rate, colour = industry, group = industry)) +
      geom_point(new_df, mapping = aes(factor(year), rate, colour = industry, group = industry)) +
      geom_line(avg_df, mapping = aes(factor(year), rate, group = 1), alpha = 0.4, linetype = 'dashed') +
      scale_y_continuous(labels = percent_format(accuracy = 1L)) + 
      labs(x = '', y = 'Rate', colour = 'Industry', caption = "dashed line is the average")
  } else {
    ggplot() + 
      geom_line(new_df, mapping = aes(factor(year), count, colour = industry, group = industry)) +
      geom_point(new_df, mapping = aes(factor(year), count, colour = industry, group = industry)) +
      geom_line(avg_df, mapping = aes(factor(year), count, group = 1), alpha = 0.4, linetype = 'dashed') +
      labs(x = '', y = 'Count', colour = 'Industry', caption = "dashed line is the average")
  }   
}

# plot 3
make_plot_3 <- function(industries = c("Agriculture", "Construction"), year_desired = 2000, stat = "rate"){
  avg_df <- unemply_df_month %>%
    group_by(month) %>%
    summarize(rate = mean(rate),
              count = mean(count))
  
  new_df <- unemply_df_month %>%
    filter(year == year_desired,
           industry %in% industries)
  if(stat == "rate"){
    ggplot() + 
      geom_line(new_df, mapping = aes(factor(month), rate, colour = industry, group = industry)) +
      geom_point(new_df, mapping = aes(factor(month), rate, colour = industry, group = industry)) +
      geom_line(avg_df, mapping = aes(month, rate), alpha = 0.4, linetype = 'dashed') +
      scale_y_continuous(labels = percent_format(accuracy = 1L)) + 
      scale_x_discrete(breaks = seq_along(1:12), labels=c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
                                                          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")) +
      labs(x = '', y = 'Rate', colour = 'Industry', caption = "dashed line is the average")
  } else {
    ggplot() + 
      geom_line(new_df, mapping = aes(factor(month), count, colour = industry, group = industry)) +
      geom_point(new_df, mapping = aes(factor(month), count, colour = industry, group = industry)) +
      geom_line(avg_df, mapping = aes(month, count), alpha = 0.4, linetype = 'dashed') +
      scale_x_discrete(breaks = seq_along(1:12), labels=c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
                                                          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")) +
      labs(x = '', y = 'Count', colour = 'Industry', caption = "dashed line is the average")
    
  }
}

```

```{r, echo = FALSE, fig.height=7, fig.width=12}
library(cowplot)
plot_grid(make_plot_2(), make_plot_3(), make_plot_1())


```







